spring.datasource.url=jdbc:postgresql://postgres:5432/ekart
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.cache.type=none

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Disable logtail
logging.level.com.logtail=OFF

server.port=8000

# Stripe Fix
stripeApiKey=dummy-stripe-key-for-docker
stripe.endpoint.secret=dummy-stripe-secret-for-docker



